SELECT
	DATEADD(DD, 7 - CHOOSE(DATEPART(DW, TRANSACTION_DATE), 2, 3, 4, 5, 6, 7, 1), TRANSACTION_DATE) AS WEEK_DATE
	, PART_GROUP2
	, SUM(QUANTITY) AS QUANTITY
FROM
	COMM.FCST.NEW_USAGE_ALL_VW (NOLOCK)
WHERE
	PART_GROUP2 IS NOT NULL
AND
	ORG_GROUP2 NOT IN ('CONSIGNED', 'WIRELESS CON', 'SERVICE')
GROUP BY
	DATEADD(DD, 7 - CHOOSE(DATEPART(DW, TRANSACTION_DATE), 2, 3, 4, 5, 6, 7, 1), TRANSACTION_DATE)
	, PART_GROUP2
ORDER BY
	DATEADD(DD, 7 - CHOOSE(DATEPART(DW, TRANSACTION_DATE), 2, 3, 4, 5, 6, 7, 1), TRANSACTION_DATE) ASC;